/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DeltaProtoDriver */

#ifndef _Included_DeltaProtoDriver
#define _Included_DeltaProtoDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DeltaProtoDriver
 * Method:    openPort
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_DeltaProtoDriver_openPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     DeltaProtoDriver
 * Method:    closePort
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_DeltaProtoDriver_closePort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     DeltaProtoDriver
 * Method:    moveTo
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_DeltaProtoDriver_moveTo
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     DeltaProtoDriver
 * Method:    setVar
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_DeltaProtoDriver_setVar
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     DeltaProtoDriver
 * Method:    getVar
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_DeltaProtoDriver_getVar
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
